#!bin/bash
a=3
b=4
c=O
somme=$((a + b))
somme=$((a + b + c))
produit=$((a * b))
reste=$((a - b))
carre a=$((a * a))
echo "la somme est : $somme"
echo "la somme est : $somme"
echo "le produit est :$produit"
echo "le reste est :$reste"
echo "le carré de a est : $carre a"
